name: Deploy application

  on:
    push:
      brances:
        - master

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout source code
          uses: actions/checkout@v

        - name: setup docker buildx
          uses: docker/setup-buildx-action@v2

        - name: docker login
          uses: docker/login-action@v2
          with:
            username: garciajoem4@gmail.com
            password: 52h3;F4#dh!@ZCt

        - name: build and push api
          id: build-push-api
          uses: docker/build-push-action@v3
          with:
            context: .
            file: Dockerfile
            push: true
            tags: garciajoem4@gmail.com/growth-club-docker:latest


    deploy:
      needs: build
      runs-on: self-hosted
      steps:
        - name: Pull image from docker hub
          run: docker pull growth-club-docker:latest
        # - name: Delete old docker container
        #   run: docker rm -f <container_name>
        - name: Run docker container
          run: docker run -d- p 3000:3000 --name growth-club-container growth-club-docker